
#base
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/kuyashi?useUnicode=true&characterEncoding=utf-8&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&zeroDateTimeBehavior=convertToNull&allowPublicKeyRetrieval=true
    username: root
    password: abcd1234
    driver-class-name: com.mysql.cj.jdbc.Driver

logging:
  level:
   root: warn
   org.asuka.export.dao.mapper: DEBUG
   org.asuka.export: INFO
   org.springframework: WARN
   org.mybatis: ERROR

# docPath: "d:\\doc"
docPath: "c:\\asuka\\kuyashi-project\\config"
fileType: ".xlsx"
# split by ,
#readFilesName: "keyword1000-2000,keyword3001-3100(1754995117),keyword3101-3200(286262015),keyword6000-7000(418165284)"
readFilesName: "tag,tag_function"

# export type，1：mysql，2：json file
exportType: 2

# json config
json.exportPath: "d:\\doc\\jsonCfg\\"

# mysql config
mysql.tablePrefix: "k_"
mysql.createInfoRowNum: 4
mysql.dropTableBeforeCreate: true




