
#base
cfg:
  datasource:
    jdbc-url: jdbc:mysql://127.0.0.1:3306/excel2mysql?useUnicode=true&characterEncoding=utf-8&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&zeroDateTimeBehavior=convertToNull
    username: root
    password: abcd1234
    driver-class-name: com.mysql.cj.jdbc.Driver
#    type: com.alibaba.druid.pool.DruidDataSource

logging:
  level:
   root: warn
   org.asuka.export.dao.mapper: DEBUG
   org.asuka.export: INFO
   org.springframework: WARN
   org.mybatis: ERROR

# export type，1：mysql，2：json file
exportType: 1
exportPath: "d:\\doc\\jsonCfg\\"

docPath: "d:\\doc"
fileType: ".xlsx"
tablePrefix: "cfg_"
createInfoRowNum: 4

#split by ,
readFilesName: "cfg_example"

